// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmCFNntwz6e9ljuPiqRJZoJOxkgYu-cc',
    appId: '1:467715901519:web:454959fa6aa13a4348823a',
    messagingSenderId: '467715901519',
    projectId: 'mcaflex-e3793',
    authDomain: 'mcaflex-e3793.firebaseapp.com',
    storageBucket: 'mcaflex-e3793.firebasestorage.app',
    measurementId: 'G-94P41M940H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuap_uQFEfu-Zpou3dOzfCOnf-kXLzvc',
    appId: '1:467715901519:android:d3f183c8ee6cf0df48823a',
    messagingSenderId: '467715901519',
    projectId: 'mcaflex-e3793',
    storageBucket: 'mcaflex-e3793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8dxkZg-akuHJPcNH3BAfqmjeq_Ga73sw',
    appId: '1:467715901519:ios:588ad7c50cb8ad2b48823a',
    messagingSenderId: '467715901519',
    projectId: 'mcaflex-e3793',
    storageBucket: 'mcaflex-e3793.firebasestorage.app',
    androidClientId: '467715901519-k9p34a0ehlmal4kif6q26njsl5mjv0pd.apps.googleusercontent.com',
    iosClientId: '467715901519-s1es8k04emon6qpih12o90c5j80vkboa.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcaflex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZmCFNntwz6e9ljuPiqRJZoJOxkgYu-cc',
    appId: '1:467715901519:web:56bedbdccc832f7448823a',
    messagingSenderId: '467715901519',
    projectId: 'mcaflex-e3793',
    authDomain: 'mcaflex-e3793.firebaseapp.com',
    storageBucket: 'mcaflex-e3793.firebasestorage.app',
    measurementId: 'G-QFJ8MJG013',
  );

}